### ISSUE TITLE
"White spot" on the bottom right corner?

### ISSUE THREAD

**Issue by samleemc** [fv0/native-ui#92] opened 2018-08-20 17:15 UTC
<img width="312" alt="screen shot 2018-08-21 at 1 14 11 am" src="https://user-images.githubusercontent.com/42374700/44355572-891f6b00-a4df-11e8-9f49-929357aeaff5.png">

For some reason, there is a "white spot" on my bottom right corner of my atom editor after using the Native-UI theme with the Atom Dark Syntax.

Does anyone have any idea?

**Comment by samleemc** [comment] 2018-08-22 16:38
Anyone please?? This is really annoying.

**Comment by fv0** [comment] 2018-08-23 09:07
Hi @samleemc, it would be good if you could one-by-one deactivate all packages you have installed to find the package messing with this. Maybe if you inspect the area with DevTools you can see what is causing this display error. This is the first time someone reported this, so I assume that this isn’t happening to others.

**Comment by hhc8qsed** [comment] 2018-08-31 09:12
Hi @fv0, yeah I can confirm this is reproducible (although somewhat inconsistently).

### Description
This is related to scroll bar hiding in macOS. If "Show scroll bars" is set to "always" then these spots will appear when the window and content are sized in a way that one of both scrollbars are not visible. 

These spots are actually the scrollbar corner divs with class "scrollbar-corner".

### How to reproduce
This is not always reproducible. While looking into this, sometimes everything will render correctly, although after a few tries I was able to get this to reproduce on two different Macs, both running the latest version of High Sierra and Atom.

1. In the System Preferences' General Pane, set "Show scroll bars" to "Always". 
2. Start with clean Atom settings (delete the ~/.atom directory).
3. Install the super sweet native-ui theme, and activate it.
4. Open different tabs with different sizes, you should see these scrollbar corners render incorrectly when at least one scrollbar is not visible (horizontal or vertical).
 

*Updated this after investigating further.

**Comment by hhc8qsed** [comment] 2018-09-02 05:11
Actually, this isn't specific to `native-ui`, the problem exists with the prepackaged `Atom Light` and `Atom Dark` themes as well. Seems to be a problem with how Atom renders the scrollbar-corners.

Attached a screenshot from a vanilla install, using the same steps above except with the `Atom Light `theme and `Atom Dark` syntax theme. 

![one_light_theme_with_one_dark_syntax_theme](https://user-images.githubusercontent.com/20542150/44952375-9d922a80-ae32-11e8-9d2a-ccc78ce948cb.png)

The default `One Light` and `One Dark` themes don't exhibit this problem however. @fv0 What do you think about patterning the scrollbars off how those themes implement them? 

Looks like they have special code here to handle the "always show scrollbars situation": https://github.com/atom/one-dark-ui/blob/200b6bf9188bfe990354f04b52102ff1a6d25131/styles/atom.less#L16

**Comment by hhc8qsed** [comment] 2018-09-03 05:08
Just took a stab at this with PR #93.

**Comment by fv0** [comment] 2018-09-03 08:43
@hanslivingstone Thanks so much. I’ll have a look at what you did and test it! This is what I love about the Open Source community, build better together :-)

**Comment by fv0** [comment] 2018-10-31 16:07
Should be fixed with [latest release](https://github.com/fv0/native-ui/releases/tag/v0.27.0).

**Closed as completed by fv0** 2018-10-31 16:07 UTC
Labels: Needs more info
